name: uts_pemob
description: "A new Flutter project."
environment:
  sdk: '>=3.0.0 <4.0.0'

# BAGIAN BAHAN-BAHAN UTAMA
dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5

# BAGIAN PERALATAN (UNTUK TESTING)
dev_dependencies:
  flutter_test:
    sdk: flutter