name: uts_pemob
description: "A new Flutter project."
environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  confetti: ^0.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: CustomFont
      fonts:
        - asset: assets/fonts/MomoTrustDisplay-Regular.ttf

    - family: QuestionFont
      fonts:
        - asset: assets/fonts/Boldonse-Regular.ttf